#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=NbBlip
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=10:00:00
#SBATCH --mem=64000M
#SBATCH --output=delete_me_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Your job starts in the directory where you call sbatch
# Activate your environment
source activate dl2
# Run your code
jupyter nbconvert --to notebook --execute Chat_with_BLIP_2.ipynb --output=out_Chat_with_BLIP_2.ipynb --ExecutePreprocessor.timeout=-1