model:
  arch: blip2_t5_int8
  model_type: pretrain_flant5xxl
  use_grad_checkpoint: False

paths:
  cache_root: export/

datasets:
  coco_vqa: # name of the dataset builder
    data_dir: datasets
    type: eval
    vis_processor:
        eval:
          name: "blip_image_eval"
          image_size: 224
    text_processor:
        eval:
          name: "blip_question"
    build_info:
        images:
          storage: 'coco/images/'

run:
  task: vqa
  # optimization-specific
  batch_size_train: 16
  batch_size_eval: 16
  num_workers: 4

  # inference-specific
  max_len: 10
  min_len: 1
  num_beams: 5
  inference_method: "generate"
  prompt: "Question: {} Short answer:"

  seed: 42
  output_dir: "output/VQA/Flan5XXL"

  evaluate: True
  test_splits: ["val"]

  # distribution-specific
  device: "cuda"
  world_size: 2
  dist_url: "env://"
  distributed: True